### ISSUE TITLE
Member page does not exist

### ISSUE THREAD

**Issue by Nikronic** [iust-projects/iust-projects.github.io#10]
Hi @soroushjavdan 

I can create a page for you but as some of info can be customized such as id and about, it would be better if you create your own member page.

Thanks

**Comment by soroushjavdan** [comment]
Hi @Nikronic 

Thanks for your reminder. I am kinda busy the following week, but I definitely will create it.

**Comment by Nikronic** [comment]
Of course, whenever you want. I just thought you may have forgot about it.
So I let this issue as it is as github itself would close it upon your PR.

Bests

**Comment by Nikronic** [comment]
#11 merged.

**Comment by Nikronic** [comment]
![image](https://user-images.githubusercontent.com/32401852/76698893-ec25b380-66bc-11ea-9960-c734461d6fed.png)
That's strange by the way, PR did not not close the issue. But in PR page, automatic message shows it has been closed!

**Comment by avestura** [comment]
> That's strange by the way, PR did not not close the issue. But in PR page, automatic message shows it has been closed!

I guess it's because of [this RFC](https://github.community/t5/How-to-use-Git-and-GitHub/How-to-organize-auto-closed-issues-solved-on-master-branch-but/m-p/29636#M8287). GitHub probably won't auto-close issues anymore until a release containing that commit. It makes sense when you look at new Github literature:

_0xaryan linked an issue that may be closed by this pull request_

@Nikronic

**Comment by Nikronic** [comment]
But here it says it triggers on merge 
![image](https://user-images.githubusercontent.com/32401852/76703286-f27c5580-66e5-11ea-9186-f5d38c2bd3d2.png)

I usually use "fix" keywork in my commit to make sure it will happen. IDK

@0xaryan

**Comment by avestura** [comment]
Yeah I saw that. Maybe that message is outdated. Who cares tho xD.
